2021-01-17 21:52:43,896 CRITICAL Debug.py 90 Failed to reload cog: Command raised an exception: ExtensionNotLoaded: Extension 'Cogs.stuff' has not been loaded.
2021-01-17 21:52:44,046 ERROR Debug.py 96 Command raised an exception: ExtensionNotLoaded: Extension 'Cogs.stuff' has not been loaded.
2021-01-18 02:05:48,203 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:06:03,374 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:07:23,296 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:09:58,272 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:11:05,836 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:11:26,077 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:11:42,297 ERROR Shared.py 34 Command raised an exception: TypeError: check_trades() takes 0 positional arguments but 1 was given
2021-01-18 02:14:51,328 ERROR Shared.py 34 Command raised an exception: TypeError: check_trades() takes 0 positional arguments but 1 was given
2021-01-18 02:15:43,096 ERROR Shared.py 34 Command raised an exception: TypeError: check_trades() takes 0 positional arguments but 1 was given
2021-01-18 02:16:09,669 ERROR Shared.py 34 Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'posted_trades.txt'
2021-01-18 02:18:06,333 ERROR Shared.py 34 Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: '../../posted_trades.txt'
2021-01-18 02:18:25,872 ERROR Shared.py 34 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:27:23,558 ERROR Shared.py 35 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:38:36,251 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:39:12,412 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:39:55,888 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:40:02,252 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 15:20:38,615 ERROR Shared.py 42 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 15:43:02,172 ERROR Shared.py 47 Command raised an exception: KeyError: 'trades'
2021-01-18 15:43:50,105 ERROR Shared.py 47 Command raised an exception: NameError: name 'discord' is not defined
2021-01-18 15:44:03,321 ERROR Shared.py 47 Command raised an exception: NameError: name 'discord' is not defined
2021-01-18 15:44:32,155 ERROR Shared.py 47 Command raised an exception: NameError: name 'discord' is not defined
2021-01-18 15:44:53,667 ERROR Shared.py 47 Command raised an exception: TypeError: send() takes no keyword arguments
2021-01-18 15:47:47,788 ERROR Shared.py 47 Command raised an exception: TypeError: send() takes no keyword arguments
2021-01-18 15:55:16,783 ERROR Shared.py 48 Command raised an exception: AttributeError: 'coroutine' object has no attribute 'to_dict'
2021-01-18 16:06:16,660 ERROR Shared.py 48 Command raised an exception: KeyError: 'name'
2021-01-18 16:14:55,517 ERROR Shared.py 52 Command raised an exception: TypeError: an integer is required (got type str)
2021-01-18 16:15:19,310 ERROR Shared.py 52 Command raised an exception: ValueError: year 52134 is out of range
2021-01-18 16:17:37,753 ERROR Shared.py 52 Command raised an exception: TypeError: 'EmbedProxy' object is not callable
2021-01-18 16:27:08,121 ERROR Shared.py 52 Command raised an exception: NameError: name 'time_eastern' is not defined
2021-01-18 16:27:45,104 ERROR Shared.py 52 Command raised an exception: NameError: name 'time_eastern' is not defined
2021-01-18 16:30:46,300 ERROR Shared.py 52 Command raised an exception: KeyError: 'trades'
2021-01-18 16:32:23,711 ERROR Shared.py 52 Command raised an exception: UnboundLocalError: local variable 'trade' referenced before assignment
2021-01-18 16:32:34,667 ERROR Shared.py 52 Command "trade" is not found
2021-01-18 16:36:54,267 ERROR Shared.py 52 Command raised an exception: UnsupportedOperation: not readable
2021-01-18 23:39:13,586 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-18 23:40:02,602 ERROR Shared.py 57 Command raised an exception: UserNotFound: sprx97
2021-01-18 23:46:42,417 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-18 23:48:10,204 ERROR Shared.py 57 sprx97
2021-01-18 23:49:55,179 ERROR Shared.py 56 sprx97
2021-01-19 00:06:43,223 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-19 00:06:48,766 ERROR Shared.py 57 Command raised an exception: UnboundLocalError: local variable 'user' referenced before assignment
2021-01-19 00:07:24,065 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-19 00:07:25,589 ERROR Shared.py 57 Command raised an exception: NameError: name 'results' is not defined
2021-01-19 00:07:41,982 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-19 00:07:47,612 ERROR Shared.py 57 asdfasdf
2021-01-19 00:08:42,126 ERROR Shared.py 57 asdfasdfasdf
