2021-01-16 18:16:34,179 ERROR Memes.py 13 oops
2021-01-17 21:52:44,043 ERROR Memes.py 53 Command raised an exception: ExtensionNotLoaded: Extension 'Cogs.stuff' has not been loaded.
2021-01-18 02:05:48,203 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:06:03,376 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:07:23,297 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:09:58,273 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:11:05,838 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:11:26,078 ERROR Shared.py 34 Command raised an exception: NameError: name 'check_trades' is not defined
2021-01-18 02:11:42,298 ERROR Shared.py 34 Command raised an exception: TypeError: check_trades() takes 0 positional arguments but 1 was given
2021-01-18 02:14:51,329 ERROR Shared.py 34 Command raised an exception: TypeError: check_trades() takes 0 positional arguments but 1 was given
2021-01-18 02:15:43,099 ERROR Shared.py 34 Command raised an exception: TypeError: check_trades() takes 0 positional arguments but 1 was given
2021-01-18 02:16:09,672 ERROR Shared.py 34 Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'posted_trades.txt'
2021-01-18 02:18:06,335 ERROR Shared.py 34 Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: '../../posted_trades.txt'
2021-01-18 02:18:25,878 ERROR Shared.py 34 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:27:23,560 ERROR Shared.py 35 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:38:36,254 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:39:12,414 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:39:55,890 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 02:40:02,746 ERROR Shared.py 40 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 15:20:38,618 ERROR Shared.py 42 Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
2021-01-18 15:43:02,174 ERROR Shared.py 47 Command raised an exception: KeyError: 'trades'
2021-01-18 15:43:50,106 ERROR Shared.py 47 Command raised an exception: NameError: name 'discord' is not defined
2021-01-18 15:44:03,323 ERROR Shared.py 47 Command raised an exception: NameError: name 'discord' is not defined
2021-01-18 15:44:32,157 ERROR Shared.py 47 Command raised an exception: NameError: name 'discord' is not defined
2021-01-18 15:44:53,669 ERROR Shared.py 47 Command raised an exception: TypeError: send() takes no keyword arguments
2021-01-18 15:47:47,790 ERROR Shared.py 47 Command raised an exception: TypeError: send() takes no keyword arguments
2021-01-18 15:55:16,785 ERROR Shared.py 48 Command raised an exception: AttributeError: 'coroutine' object has no attribute 'to_dict'
2021-01-18 16:06:16,661 ERROR Shared.py 48 Command raised an exception: KeyError: 'name'
2021-01-18 16:14:55,520 ERROR Shared.py 52 Command raised an exception: TypeError: an integer is required (got type str)
2021-01-18 16:15:19,313 ERROR Shared.py 52 Command raised an exception: ValueError: year 52134 is out of range
2021-01-18 16:17:37,755 ERROR Shared.py 52 Command raised an exception: TypeError: 'EmbedProxy' object is not callable
2021-01-18 16:27:08,124 ERROR Shared.py 52 Command raised an exception: NameError: name 'time_eastern' is not defined
2021-01-18 16:27:45,107 ERROR Shared.py 52 Command raised an exception: NameError: name 'time_eastern' is not defined
2021-01-18 16:30:46,302 ERROR Shared.py 52 Command raised an exception: KeyError: 'trades'
2021-01-18 16:32:23,713 ERROR Shared.py 52 Command raised an exception: UnboundLocalError: local variable 'trade' referenced before assignment
2021-01-18 16:32:34,669 ERROR Shared.py 52 Command "trade" is not found
2021-01-18 16:36:54,269 ERROR Shared.py 52 Command raised an exception: UnsupportedOperation: not readable
2021-01-18 23:39:13,589 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-18 23:40:02,614 ERROR Shared.py 57 Command raised an exception: UserNotFound: sprx97
2021-01-18 23:46:42,421 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-18 23:48:10,206 ERROR Shared.py 57 sprx97
2021-01-18 23:49:55,181 ERROR Shared.py 56 sprx97
2021-01-19 00:06:43,226 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-19 00:06:48,768 ERROR Shared.py 57 Command raised an exception: UnboundLocalError: local variable 'user' referenced before assignment
2021-01-19 00:07:24,067 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-19 00:07:25,591 ERROR Shared.py 57 Command raised an exception: NameError: name 'results' is not defined
2021-01-19 00:07:41,984 ERROR Shared.py 57 user is a required argument that is missing.
2021-01-19 00:07:47,615 ERROR Shared.py 57 asdfasdf
2021-01-19 00:08:42,128 ERROR Shared.py 57 asdfasdfasdf
